version: "3"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - "./:/app"
    links:
      - postgres
    ports:
      - 3000:3000

  migrate-db:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - "./:/app"
    links:
      - postgres
    command: npm run migrate:up

  postgres:
    image: postgres:latest
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432

  migrate:
    build:
      dockerfile: Dockerfile
      context: .
    links:
      - postgres
    command: npm run migrate:up
